#!/usr/bin/env bash
set -eux
jupyter lab clean --all

pushd qtheme
jlpm cache clean
jlpm bootstrap
# jupyter labextension install $(cat labex.txt) --no-build
jupyter labextension list
jupyter lab build --debug
popd

mv overrides.json /srv/conda/envs/notebook/share/jupyter/lab/settings