#!/usr/bin/env bash
set -eux
mv overrides.json /srv/conda/envs/notebook/share/jupyter/lab/settings
jupyter lab clean --all
jlpm cache clean
jlpm bootstrap
# jupyter labextension install $(cat labex.txt) --no-build
jupyter labextension list
jupyter lab build --debug
